/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version + capability handshake (unauthenticated); ?client lets the server judge compatibility */
        get: operations["handshake"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a GitHub user token (from the OAuth device flow) for a server session (unauthenticated) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent runs for an app */
        get: operations["listRuns"];
        put?: never;
        /** Enqueue a run */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        /** Cancel a run */
        delete: operations["cancelRun"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE stream of RunEvents; Last-Event-ID resumes from the given seq */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["askRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["continueRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApps"];
        put?: never;
        /** Create or validate an app config */
        post: operations["createApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApp"];
        put: operations["updateApp"];
        post?: never;
        delete: operations["deleteApp"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{name}/intelligence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learning ledger, value-oracle scorecard and curriculum for an app (read-only) */
        get: operations["getAppIntelligence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run-scoped report: the current-execution analysis plus the evolution-as-of-the-run (read-only) */
        get: operations["getRunReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{name}/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Period-over-period trends for an app: coverage, value-oracle, verdicts, error classes (read-only) */
        get: operations["getAppTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{name}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ad-hoc report: interestingness-ranked insights with a recommended chart per metric (read-only) */
        get: operations["getAppReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fleet-wide integrity readout: ground-truth value-oracle vs. proxy pass-rate (read-only) */
        get: operations["getSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRepos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/help": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["help"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgentConfig"];
        put: operations["updateAgentConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgentModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restartAgentProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RunEvent: {
            seq: number;
            runId: string;
            ts: number;
            body: components["schemas"]["RunEventBody"];
        };
        RunEventBody: {
            /** @enum {string} */
            type: "run.started";
            app: string;
            sha: string;
            /** @enum {string} */
            mode: "diff" | "complete" | "exhaustive" | "manual" | "context";
            /** @enum {string} */
            target: "e2e" | "code";
        } | {
            /** @enum {string} */
            type: "step.changed";
            /** @enum {string} */
            step: "gate" | "classify" | "setup" | "generate" | "validate" | "health" | "execute" | "coverage" | "retry" | "decide" | "done";
            detail?: string;
        } | {
            /** @enum {string} */
            type: "agent.activity";
            /** @enum {string} */
            kind: "analyzing" | "writing" | "command" | "subagent";
            target: string;
            /** @enum {string} */
            status: "running" | "completed";
            callId?: string;
            workerId?: string;
        } | {
            /** @enum {string} */
            type: "plan.updated";
            todos: {
                content: string;
                /** @enum {string} */
                status: "pending" | "in_progress" | "completed" | "cancelled";
            }[];
        } | {
            /** @enum {string} */
            type: "spec.written";
            file: string;
        } | {
            /** @enum {string} */
            type: "test.discovered";
            name: string;
            file?: string;
        } | {
            /** @enum {string} */
            type: "test.started";
            name: string;
        } | {
            /** @enum {string} */
            type: "test.passed";
            name: string;
            durationMs: number;
        } | {
            /** @enum {string} */
            type: "test.failed";
            name: string;
            durationMs?: number;
            detail?: string;
        } | {
            /** @enum {string} */
            type: "test.flaky";
            name: string;
            attempts: number;
        } | {
            /** @enum {string} */
            type: "reviewer.verdict";
            approved: boolean;
            reasons: string[];
        } | {
            /** @enum {string} */
            type: "coverage.computed";
            changedLines: number;
            coveredLines: number;
        } | {
            /** @enum {string} */
            type: "run.verdict";
            /** @enum {string} */
            verdict: "pass" | "fail" | "flaky" | "invalid" | "infra-error" | "skipped";
            passed?: number;
            failed?: number;
            outcome?: string;
        } | {
            /** @enum {string} */
            type: "agent.error";
            detail: string;
        } | {
            /** @enum {string} */
            type: "log.line";
            /** @enum {string} */
            level: "info" | "warn" | "error";
            text: string;
        };
        RunRecord: {
            id: string;
            app: string;
            sha: string;
            ref?: string;
            /** @enum {string} */
            target: "e2e" | "code";
            /** @enum {string} */
            mode: "diff" | "complete" | "exhaustive" | "manual" | "context";
            /** @enum {string} */
            status: "enqueued" | "running" | "done";
            step?: string;
            stepDetail?: string;
            /** @enum {string} */
            verdict?: "pass" | "fail" | "flaky" | "invalid" | "infra-error" | "skipped";
            passed?: number;
            failed?: number;
            note?: string;
            retrying?: boolean;
            parentRunId?: string;
            triggerRepo?: string;
            cases: components["schemas"]["QaCase"][];
            specs?: components["schemas"]["SpecRecord"][];
            logs: string[];
            activity?: components["schemas"]["AgentActivity"][];
            stepStartedAt?: string;
            at: string;
        };
        QaCase: {
            name: string;
            /** @enum {string} */
            status: "pass" | "fail" | "flaky";
            detail?: string;
            flow?: string;
            objective?: string;
            reason?: string;
            durationMs?: number;
        };
        SpecRecord: {
            name: string;
            objective?: string;
            flow?: string;
        };
        AgentActivity: {
            /** @enum {string} */
            kind: "file" | "command" | "todo" | "phase" | "error";
            text: string;
            /** @enum {string} */
            status?: "pending" | "in_progress" | "completed";
            ts: string;
        };
        AppView: {
            name: string;
            repo: string;
            baseUrl: string;
            versionUrl: string;
            code: boolean;
            shadow: boolean;
            needsReview: boolean;
            testDataPrefix: string;
            services: components["schemas"]["AppService"][];
        };
        AppService: {
            repo: string;
            openapi?: string;
            versionUrl?: string;
        };
        QueueStatus: {
            pending: number;
            running: {
                id: string;
                app: string;
            } | null;
        };
        ChatEntry: {
            role: string;
            text: string;
        };
        VersionInfo: {
            serverVersion: string;
            apiVersion: string;
            minClientVersion: string;
            compatible: boolean;
            capabilities: string[];
            message?: string;
        };
        LoginRequest: {
            githubToken: string;
        };
        LoginResponse: {
            token: string;
            username: string;
            expiresAt: string;
        };
        CreateRunInput: {
            app: string;
            /** @enum {string} */
            target: "e2e" | "code";
            /** @enum {string} */
            mode: "diff" | "complete" | "exhaustive" | "manual" | "context";
            sha?: string;
            ref?: string;
            guidance?: string;
            shadow?: boolean;
            commits?: number;
        };
        CreateRunResult: {
            id: string;
            app: string;
            sha: string;
            /** @enum {string} */
            target: "e2e" | "code";
            /** @enum {string} */
            mode: "diff" | "complete" | "exhaustive" | "manual" | "context";
            status: string;
        };
        AskRequest: {
            question: string;
            history?: components["schemas"]["ChatEntry"][];
        };
        AskResponse: {
            answer: string;
        };
        ContinueRequest: {
            cases?: string[];
            guidance?: string;
        };
        ContinueResult: {
            id: string;
            parentRunId: string;
        };
        OnboardServiceInput: {
            repo: string;
            openapi?: string;
            versionUrl?: string;
        };
        RepoInfo: {
            name: string;
            fullName: string;
            private: boolean;
            defaultBranch: string;
            description: string | null;
        };
        CreateAppInput: {
            repo: string;
            name?: string;
            baseUrl?: string;
            versionUrl?: string;
            /** @enum {string} */
            target?: "e2e" | "code";
            needsReview?: boolean;
            shadow?: boolean;
            testDataPrefix?: string;
            services?: components["schemas"]["OnboardServiceInput"][];
            env?: {
                [key: string]: string;
            };
            dryRun?: boolean;
            validateOnly?: boolean;
        };
        UpdateAppInput: {
            repo?: string;
            baseUrl?: string;
            versionUrl?: string;
            /** @enum {string} */
            target?: "e2e" | "code";
            needsReview?: boolean;
            shadow?: boolean;
            testDataPrefix?: string;
            services?: components["schemas"]["OnboardServiceInput"][];
            env?: {
                [key: string]: string;
            };
            dryRun?: boolean;
        };
        CreateAppResult: {
            ok: boolean;
            errors?: string[];
            repoInfo?: components["schemas"]["RepoInfo"];
            yaml?: string;
            name?: string;
            path?: string;
            envApplied?: string[];
            warnings?: string[];
        };
        DeleteAppResult: {
            removed: string[];
        };
        RepoListItem: {
            fullName: string;
            private: boolean;
            description: string | null;
        };
        RepoListResponse: {
            repos: components["schemas"]["RepoListItem"][];
            hasMore: boolean;
        };
        PublicAgentConfig: {
            /** @enum {string} */
            mode: "single" | "dual";
            /** @enum {string} */
            singleProvider: "opencode" | "codex";
            assignments: {
                primary: components["schemas"]["RoleAssignment"];
                reviewer: components["schemas"]["RoleAssignment"];
                chat: components["schemas"]["RoleAssignment"];
            };
            keys: {
                opencode: boolean;
                codex: boolean;
            };
            validation: {
                ok: boolean;
                errors: string[];
                requiresSingleDowngradeConfirmation?: boolean;
                /** @enum {string} */
                downgradeProvider?: "opencode" | "codex";
            };
            health?: {
                opencode?: components["schemas"]["AgentProviderHealth"];
                codex?: components["schemas"]["AgentProviderHealth"];
            };
        };
        AgentConfigUpdate: {
            /** @enum {string} */
            mode?: "single" | "dual";
            /** @enum {string} */
            singleProvider?: "opencode" | "codex";
            assignments?: {
                primary?: components["schemas"]["RoleAssignment"];
                reviewer?: components["schemas"]["RoleAssignment"];
                chat?: components["schemas"]["RoleAssignment"];
            };
            apiKeys?: {
                opencode?: string;
                codex?: string;
            };
            confirmSingleDowngrade?: boolean;
        };
        AgentConfigApplyResult: {
            config: components["schemas"]["PublicAgentConfig"];
            restarted: ("opencode" | "codex")[];
            downgraded?: boolean;
        };
        AgentModelsResponse: {
            /** @enum {string} */
            provider: "opencode" | "codex";
            models: components["schemas"]["AgentModelInfo"][];
        };
        AgentRestartRequest: {
            /** @enum {string} */
            provider: "opencode" | "codex";
        };
        AgentRestartResponse: {
            health: components["schemas"]["AgentProviderHealth"];
        };
        AgentProviderHealth: {
            /** @enum {string} */
            provider: "opencode" | "codex";
            /** @enum {string} */
            status: "stopped" | "starting" | "healthy" | "degraded" | "failed" | "needs_config";
            configured: boolean;
            error?: string;
        };
        AgentModelInfo: {
            id: string;
            label?: string;
            /** @enum {string} */
            provider?: "opencode" | "codex";
        };
        RoleAssignment: {
            /** @enum {string} */
            provider: "opencode" | "codex";
            model: string;
        };
        LearningRuleView: {
            trigger: string;
            action: string;
            errorClass: string;
            /** @enum {string} */
            confidence: "low" | "medium" | "high";
            usageCount: number;
            outcomeCount: number;
            successRate: number | null;
            /** @enum {string} */
            status: "candidate" | "active" | "deprecated" | "superseded";
        };
        ScorecardView: {
            updatedAt: string;
            totalRuns: number;
            measuredRuns: number;
            avgValueScore: number | null;
            lastValueScore: number | null;
            entries: {
                valueScore: number | null;
                mutantCount: number;
                killedCount: number;
                target: string;
                at: string;
            }[];
        };
        CurriculumView: {
            updatedAt: string;
            archetypes: {
                archetype: string;
                caughtRealBug: boolean;
                promotionCount: number;
            }[];
        };
        IntelligenceView: {
            app: string;
            rules: components["schemas"]["LearningRuleView"][];
            scorecard: components["schemas"]["ScorecardView"] | null;
            curriculum: components["schemas"]["CurriculumView"] | null;
        };
        SignalsView: {
            valueOracle: {
                measured: boolean;
                avgScore: number | null;
                measuredRuns: number;
                totalRuns: number;
            };
            reviewer: {
                passRate: number | null;
                runs: number;
            };
            coverage: {
                measured: boolean;
                avgRatio: number | null;
                measuredRuns: number;
                totalRuns: number;
            };
        };
        TrendWindow: {
            current: number;
            previous: number;
        };
        CoverageTrend: {
            measured: boolean;
            ratio: number | null;
            previousRatio: number | null;
            minRatio: number;
            series: number[];
        };
        ValueTrend: {
            measured: boolean;
            avgScore: number | null;
            previousAvgScore: number | null;
            series: number[];
        };
        FlakyTrend: {
            rate: number | null;
            previousRate: number | null;
            runs: number;
        };
        ErrorClassCount: {
            errorClass: string;
            count: number;
            previousCount: number;
            multiplier: number | null;
        };
        TrendsView: {
            app: string;
            generatedAt: string;
            window: components["schemas"]["TrendWindow"];
            coverage: components["schemas"]["CoverageTrend"];
            valueOracle: components["schemas"]["ValueTrend"];
            verdictMix: {
                [key: string]: number;
            };
            reviewerPassRate: number | null;
            flaky: components["schemas"]["FlakyTrend"];
            errorClasses: components["schemas"]["ErrorClassCount"][];
            duration: {
                avgMs: number | null;
                previousMs: number | null;
                runs: number;
            };
            flows: {
                flow: string;
                runs: number;
                flaky: number;
                fail: number;
            }[];
        };
        ReportInsight: {
            id: string;
            title: string;
            /** @enum {string} */
            intent: "single-value" | "comparison" | "trend" | "composition" | "distribution";
            /** @enum {string} */
            chart: "big-number" | "gauge" | "paired-bars" | "ranked-bars" | "stacked-bar" | "line" | "area" | "donut";
            value: number | null;
            /** @enum {string} */
            unit?: "ratio" | "percent" | "count" | "ms" | "score";
            target?: number | null;
            delta: number | null;
            multiplier: number | null;
            /** @enum {string} */
            direction: "up" | "down" | "flat";
            /** @enum {string} */
            goodWhen: "up" | "down" | "neutral";
            caption?: string;
            series?: number[];
            breakdown?: {
                label: string;
                value: number;
                /** @enum {string} */
                semantic?: "good" | "bad" | "neutral";
            }[];
            score: number;
        };
        ReportView: {
            app: string;
            generatedAt: string;
            window: components["schemas"]["TrendWindow"];
            headline: string;
            insights: components["schemas"]["ReportInsight"][];
        };
        RunReportView: {
            current: components["schemas"]["ReportView"];
            evolution: components["schemas"]["ReportView"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    handshake: {
        parameters: {
            query?: {
                client?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description server version, supported client floor and capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description session minted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description the GitHub token was rejected */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description authenticated, but not a collaborator on any watched repo */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description GitHub login is not configured on this server */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRuns: {
        parameters: {
            query: {
                app: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"][];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunInput"];
            };
        };
        responses: {
            /** @description enqueued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResult"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream. Each event uses id=<RunEvent.seq>, event=<RunEvent.body.type>, data=<RunEvent JSON>. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    askRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
        };
    };
    continueRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinueRequest"];
            };
        };
        responses: {
            /** @description continuation */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContinueResult"];
                };
            };
        };
    };
    getQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description queue depth */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueStatus"];
                };
            };
        };
    };
    listApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description configured apps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppView"][];
                };
            };
        };
    };
    createApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAppInput"];
            };
        };
        responses: {
            /** @description validated or dry-run app config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAppResult"];
                };
            };
            /** @description created app config */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAppResult"];
                };
            };
            /** @description invalid app config */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description configured app */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppView"];
                };
            };
        };
    };
    updateApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAppInput"];
            };
        };
        responses: {
            /** @description updated or dry-run app config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAppResult"];
                };
            };
            /** @description invalid app config */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteApp: {
        parameters: {
            query?: {
                purge?: boolean;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted app config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteAppResult"];
                };
            };
        };
    };
    getAppIntelligence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description intelligence view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceView"];
                };
            };
        };
    };
    getRunReport: {
        parameters: {
            query?: {
                window?: number;
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description run report view (current + evolution) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunReportView"];
                };
            };
            /** @description run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAppTrends: {
        parameters: {
            query?: {
                window?: number;
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description trends view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsView"];
                };
            };
        };
    };
    getAppReport: {
        parameters: {
            query?: {
                window?: number;
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description report view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportView"];
                };
            };
        };
    };
    getSignals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description signals view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsView"];
                };
            };
        };
    };
    listRepos: {
        parameters: {
            query: {
                owner: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description repositories visible to the control plane */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoListResponse"];
                };
            };
        };
    };
    help: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
        };
    };
    getAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description agent runtime config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicAgentConfig"];
                };
            };
        };
    };
    updateAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigUpdate"];
            };
        };
        responses: {
            /** @description updated runtime config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigApplyResult"];
                };
            };
            /** @description active run/session or downgrade confirmation required */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAgentModels: {
        parameters: {
            query: {
                provider: "opencode" | "codex";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description models for provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentModelsResponse"];
                };
            };
        };
    };
    restartAgentProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRestartRequest"];
            };
        };
        responses: {
            /** @description provider health after restart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRestartResponse"];
                };
            };
            /** @description active run/session */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
