// Minimal, self-contained source-map consumer for change-coverage. A production frontend (Angular,
// React, …) serves HASHED, BUNDLED JS (main.a1b2c3.js); V8 coverage reports cover BYTES of that
// bundle, whose URL never matches a repo source path. Without a source map, the keystone is
// permanently "unknown" for any bundled deploy. This decodes the bundle's source map (the VLQ
// `mappings`) and translates covered bundle positions back to ORIGINAL source files + lines.
//
// Pure and dependency-free (the `source-map` npm package is WASM-based and only a transitive dep —
// too fragile for the execution path). Only the slice we need: decode mappings, then for each
// mapping segment whose generated position is COVERED, mark the original (source, line) covered.

export interface RawSourceMap {
  version?: number;
  sources: string[];
  sourcesContent?: (string | null)[];
  mappings: string;
  sourceRoot?: string;
}

const B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
const B64_LOOKUP: Record<string, number> = {};
for (let i = 0; i < B64.length; i++) B64_LOOKUP[B64[i]!] = i;

// Decode one base64-VLQ-encoded segment string into its integer fields.
export function decodeVlq(segment: string): number[] {
  const result: number[] = [];
  let shift = 0;
  let value = 0;
  for (const ch of segment) {
    const digit = B64_LOOKUP[ch];
    if (digit === undefined) continue;
    const hasContinuation = digit & 32;
    value += (digit & 31) << shift;
    if (hasContinuation) {
      shift += 5;
    } else {
      const negate = value & 1;
      value >>= 1;
      result.push(negate ? -value : value);
      value = 0;
      shift = 0;
    }
  }
  return result;
}

export interface MappingSegment {
  genLine: number; // 0-based generated (bundle) line
  genCol: number; // 0-based generated column
  sourceIndex: number; // index into map.sources
  origLine: number; // 0-based original line
  origCol: number; // 0-based original column
}

// Decode the `mappings` field into absolute segments. genCol resets per generated line; sourceIndex,
// origLine and origCol are cumulative across the whole mappings string (the source-map v3 spec).
export function decodeMappings(mappings: string): MappingSegment[] {
  const segments: MappingSegment[] = [];
  let sourceIndex = 0;
  let origLine = 0;
  let origCol = 0;
  const lines = mappings.split(";");
  for (let genLine = 0; genLine < lines.length; genLine++) {
    let genCol = 0;
    const lineStr = lines[genLine]!;
    if (!lineStr) continue;
    for (const segStr of lineStr.split(",")) {
      if (!segStr) continue;
      const f = decodeVlq(segStr);
      if (f.length === 0) continue;
      genCol += f[0]!;
      // length 1 = a generated column with no source mapping (a gap) — skip; >=4 carries source info.
      if (f.length >= 4) {
        sourceIndex += f[1]!;
        origLine += f[2]!;
        origCol += f[3]!;
        segments.push({ genLine, genCol, sourceIndex, origLine, origCol });
      }
    }
  }
  return segments;
}

// Normalize a source-map `sources` entry to a repo-relative-ish path that can be suffix-matched
// against the changed files: strip the webpack:// (or other) scheme, the sourceRoot, and ./ / leading
// slashes. e.g. "webpack:///./src/app/foo.component.ts" → "src/app/foo.component.ts".
export function normalizeSourcePath(source: string, sourceRoot?: string): string {
  let s = source;
  if (sourceRoot) s = sourceRoot.replace(/\/$/, "") + "/" + s.replace(/^\//, "");
  s = s.replace(/^[a-z-]+:\/\/+/i, ""); // webpack:///, file://, etc.
  s = s.replace(/^(\.\.\/)+/, "").replace(/^\.\//, "").replace(/^\/+/, "");
  return s;
}

// For each mapping segment whose generated byte is COVERED, mark its original (source, line) covered.
// `isByteCovered(byteOffset)` answers whether a given byte of the bundle source executed; `resolve`
// maps a normalized source path to a changed repo file (or null to ignore it). Returns repo file →
// set of 1-based original lines.
export function coveredOriginalLines(
  map: RawSourceMap,
  genLineStartOffsets: number[], // byte offset where each generated line starts (from the bundle source)
  isByteCovered: (byteOffset: number) => boolean,
  resolve: (normalizedSource: string) => string | null,
): Map<string, Set<number>> {
  const out = new Map<string, Set<number>>();
  const resolvedCache = new Map<number, string | null>();
  for (const seg of decodeMappings(map.mappings)) {
    const lineStart = genLineStartOffsets[seg.genLine];
    if (lineStart === undefined) continue;
    if (!isByteCovered(lineStart + seg.genCol)) continue; // this generated token did not execute
    let repoFile = resolvedCache.get(seg.sourceIndex);
    if (repoFile === undefined) {
      const src = map.sources[seg.sourceIndex];
      repoFile = src ? resolve(normalizeSourcePath(src, map.sourceRoot)) : null;
      resolvedCache.set(seg.sourceIndex, repoFile);
    }
    if (!repoFile) continue;
    let set = out.get(repoFile);
    if (!set) {
      set = new Set<number>();
      out.set(repoFile, set);
    }
    set.add(seg.origLine + 1); // 0-based → 1-based repo line
  }
  return out;
}
