// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package contract

// Defines values for AgentActivityKind.
const (
	Command AgentActivityKind = "command"
	Error   AgentActivityKind = "error"
	File    AgentActivityKind = "file"
	Phase   AgentActivityKind = "phase"
	Todo    AgentActivityKind = "todo"
)

// Valid indicates whether the value is a known member of the AgentActivityKind enum.
func (e AgentActivityKind) Valid() bool {
	switch e {
	case Command:
		return true
	case Error:
		return true
	case File:
		return true
	case Phase:
		return true
	case Todo:
		return true
	default:
		return false
	}
}

// Defines values for AgentActivityStatus.
const (
	Completed  AgentActivityStatus = "completed"
	InProgress AgentActivityStatus = "in_progress"
	Pending    AgentActivityStatus = "pending"
)

// Valid indicates whether the value is a known member of the AgentActivityStatus enum.
func (e AgentActivityStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case InProgress:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for AgentConfigApplyResultRestarted.
const (
	AgentConfigApplyResultRestartedCodex    AgentConfigApplyResultRestarted = "codex"
	AgentConfigApplyResultRestartedOpencode AgentConfigApplyResultRestarted = "opencode"
)

// Valid indicates whether the value is a known member of the AgentConfigApplyResultRestarted enum.
func (e AgentConfigApplyResultRestarted) Valid() bool {
	switch e {
	case AgentConfigApplyResultRestartedCodex:
		return true
	case AgentConfigApplyResultRestartedOpencode:
		return true
	default:
		return false
	}
}

// Defines values for AgentConfigUpdateMode.
const (
	AgentConfigUpdateModeDual   AgentConfigUpdateMode = "dual"
	AgentConfigUpdateModeSingle AgentConfigUpdateMode = "single"
)

// Valid indicates whether the value is a known member of the AgentConfigUpdateMode enum.
func (e AgentConfigUpdateMode) Valid() bool {
	switch e {
	case AgentConfigUpdateModeDual:
		return true
	case AgentConfigUpdateModeSingle:
		return true
	default:
		return false
	}
}

// Defines values for AgentConfigUpdateSingleProvider.
const (
	AgentConfigUpdateSingleProviderCodex    AgentConfigUpdateSingleProvider = "codex"
	AgentConfigUpdateSingleProviderOpencode AgentConfigUpdateSingleProvider = "opencode"
)

// Valid indicates whether the value is a known member of the AgentConfigUpdateSingleProvider enum.
func (e AgentConfigUpdateSingleProvider) Valid() bool {
	switch e {
	case AgentConfigUpdateSingleProviderCodex:
		return true
	case AgentConfigUpdateSingleProviderOpencode:
		return true
	default:
		return false
	}
}

// Defines values for AgentModelInfoProvider.
const (
	AgentModelInfoProviderCodex    AgentModelInfoProvider = "codex"
	AgentModelInfoProviderOpencode AgentModelInfoProvider = "opencode"
)

// Valid indicates whether the value is a known member of the AgentModelInfoProvider enum.
func (e AgentModelInfoProvider) Valid() bool {
	switch e {
	case AgentModelInfoProviderCodex:
		return true
	case AgentModelInfoProviderOpencode:
		return true
	default:
		return false
	}
}

// Defines values for AgentModelsResponseProvider.
const (
	AgentModelsResponseProviderCodex    AgentModelsResponseProvider = "codex"
	AgentModelsResponseProviderOpencode AgentModelsResponseProvider = "opencode"
)

// Valid indicates whether the value is a known member of the AgentModelsResponseProvider enum.
func (e AgentModelsResponseProvider) Valid() bool {
	switch e {
	case AgentModelsResponseProviderCodex:
		return true
	case AgentModelsResponseProviderOpencode:
		return true
	default:
		return false
	}
}

// Defines values for AgentProviderHealthProvider.
const (
	AgentProviderHealthProviderCodex    AgentProviderHealthProvider = "codex"
	AgentProviderHealthProviderOpencode AgentProviderHealthProvider = "opencode"
)

// Valid indicates whether the value is a known member of the AgentProviderHealthProvider enum.
func (e AgentProviderHealthProvider) Valid() bool {
	switch e {
	case AgentProviderHealthProviderCodex:
		return true
	case AgentProviderHealthProviderOpencode:
		return true
	default:
		return false
	}
}

// Defines values for AgentProviderHealthStatus.
const (
	Degraded    AgentProviderHealthStatus = "degraded"
	Failed      AgentProviderHealthStatus = "failed"
	Healthy     AgentProviderHealthStatus = "healthy"
	NeedsConfig AgentProviderHealthStatus = "needs_config"
	Starting    AgentProviderHealthStatus = "starting"
	Stopped     AgentProviderHealthStatus = "stopped"
)

// Valid indicates whether the value is a known member of the AgentProviderHealthStatus enum.
func (e AgentProviderHealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Failed:
		return true
	case Healthy:
		return true
	case NeedsConfig:
		return true
	case Starting:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for AgentRestartRequestProvider.
const (
	AgentRestartRequestProviderCodex    AgentRestartRequestProvider = "codex"
	AgentRestartRequestProviderOpencode AgentRestartRequestProvider = "opencode"
)

// Valid indicates whether the value is a known member of the AgentRestartRequestProvider enum.
func (e AgentRestartRequestProvider) Valid() bool {
	switch e {
	case AgentRestartRequestProviderCodex:
		return true
	case AgentRestartRequestProviderOpencode:
		return true
	default:
		return false
	}
}

// Defines values for CreateAppInputTarget.
const (
	CreateAppInputTargetCode CreateAppInputTarget = "code"
	CreateAppInputTargetE2e  CreateAppInputTarget = "e2e"
)

// Valid indicates whether the value is a known member of the CreateAppInputTarget enum.
func (e CreateAppInputTarget) Valid() bool {
	switch e {
	case CreateAppInputTargetCode:
		return true
	case CreateAppInputTargetE2e:
		return true
	default:
		return false
	}
}

// Defines values for CreateRunInputMode.
const (
	CreateRunInputModeComplete   CreateRunInputMode = "complete"
	CreateRunInputModeContext    CreateRunInputMode = "context"
	CreateRunInputModeDiff       CreateRunInputMode = "diff"
	CreateRunInputModeExhaustive CreateRunInputMode = "exhaustive"
	CreateRunInputModeManual     CreateRunInputMode = "manual"
)

// Valid indicates whether the value is a known member of the CreateRunInputMode enum.
func (e CreateRunInputMode) Valid() bool {
	switch e {
	case CreateRunInputModeComplete:
		return true
	case CreateRunInputModeContext:
		return true
	case CreateRunInputModeDiff:
		return true
	case CreateRunInputModeExhaustive:
		return true
	case CreateRunInputModeManual:
		return true
	default:
		return false
	}
}

// Defines values for CreateRunInputTarget.
const (
	CreateRunInputTargetCode CreateRunInputTarget = "code"
	CreateRunInputTargetE2e  CreateRunInputTarget = "e2e"
)

// Valid indicates whether the value is a known member of the CreateRunInputTarget enum.
func (e CreateRunInputTarget) Valid() bool {
	switch e {
	case CreateRunInputTargetCode:
		return true
	case CreateRunInputTargetE2e:
		return true
	default:
		return false
	}
}

// Defines values for CreateRunResultMode.
const (
	CreateRunResultModeComplete   CreateRunResultMode = "complete"
	CreateRunResultModeContext    CreateRunResultMode = "context"
	CreateRunResultModeDiff       CreateRunResultMode = "diff"
	CreateRunResultModeExhaustive CreateRunResultMode = "exhaustive"
	CreateRunResultModeManual     CreateRunResultMode = "manual"
)

// Valid indicates whether the value is a known member of the CreateRunResultMode enum.
func (e CreateRunResultMode) Valid() bool {
	switch e {
	case CreateRunResultModeComplete:
		return true
	case CreateRunResultModeContext:
		return true
	case CreateRunResultModeDiff:
		return true
	case CreateRunResultModeExhaustive:
		return true
	case CreateRunResultModeManual:
		return true
	default:
		return false
	}
}

// Defines values for CreateRunResultTarget.
const (
	CreateRunResultTargetCode CreateRunResultTarget = "code"
	CreateRunResultTargetE2e  CreateRunResultTarget = "e2e"
)

// Valid indicates whether the value is a known member of the CreateRunResultTarget enum.
func (e CreateRunResultTarget) Valid() bool {
	switch e {
	case CreateRunResultTargetCode:
		return true
	case CreateRunResultTargetE2e:
		return true
	default:
		return false
	}
}

// Defines values for LearningRuleViewConfidence.
const (
	High   LearningRuleViewConfidence = "high"
	Low    LearningRuleViewConfidence = "low"
	Medium LearningRuleViewConfidence = "medium"
)

// Valid indicates whether the value is a known member of the LearningRuleViewConfidence enum.
func (e LearningRuleViewConfidence) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for LearningRuleViewStatus.
const (
	Active     LearningRuleViewStatus = "active"
	Candidate  LearningRuleViewStatus = "candidate"
	Deprecated LearningRuleViewStatus = "deprecated"
	Superseded LearningRuleViewStatus = "superseded"
)

// Valid indicates whether the value is a known member of the LearningRuleViewStatus enum.
func (e LearningRuleViewStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Candidate:
		return true
	case Deprecated:
		return true
	case Superseded:
		return true
	default:
		return false
	}
}

// Defines values for PublicAgentConfigMode.
const (
	PublicAgentConfigModeDual   PublicAgentConfigMode = "dual"
	PublicAgentConfigModeSingle PublicAgentConfigMode = "single"
)

// Valid indicates whether the value is a known member of the PublicAgentConfigMode enum.
func (e PublicAgentConfigMode) Valid() bool {
	switch e {
	case PublicAgentConfigModeDual:
		return true
	case PublicAgentConfigModeSingle:
		return true
	default:
		return false
	}
}

// Defines values for PublicAgentConfigSingleProvider.
const (
	PublicAgentConfigSingleProviderCodex    PublicAgentConfigSingleProvider = "codex"
	PublicAgentConfigSingleProviderOpencode PublicAgentConfigSingleProvider = "opencode"
)

// Valid indicates whether the value is a known member of the PublicAgentConfigSingleProvider enum.
func (e PublicAgentConfigSingleProvider) Valid() bool {
	switch e {
	case PublicAgentConfigSingleProviderCodex:
		return true
	case PublicAgentConfigSingleProviderOpencode:
		return true
	default:
		return false
	}
}

// Defines values for PublicAgentConfigValidationDowngradeProvider.
const (
	PublicAgentConfigValidationDowngradeProviderCodex    PublicAgentConfigValidationDowngradeProvider = "codex"
	PublicAgentConfigValidationDowngradeProviderOpencode PublicAgentConfigValidationDowngradeProvider = "opencode"
)

// Valid indicates whether the value is a known member of the PublicAgentConfigValidationDowngradeProvider enum.
func (e PublicAgentConfigValidationDowngradeProvider) Valid() bool {
	switch e {
	case PublicAgentConfigValidationDowngradeProviderCodex:
		return true
	case PublicAgentConfigValidationDowngradeProviderOpencode:
		return true
	default:
		return false
	}
}

// Defines values for QaCaseStatus.
const (
	QaCaseStatusFail  QaCaseStatus = "fail"
	QaCaseStatusFlaky QaCaseStatus = "flaky"
	QaCaseStatusPass  QaCaseStatus = "pass"
)

// Valid indicates whether the value is a known member of the QaCaseStatus enum.
func (e QaCaseStatus) Valid() bool {
	switch e {
	case QaCaseStatusFail:
		return true
	case QaCaseStatusFlaky:
		return true
	case QaCaseStatusPass:
		return true
	default:
		return false
	}
}

// Defines values for RoleAssignmentProvider.
const (
	RoleAssignmentProviderCodex    RoleAssignmentProvider = "codex"
	RoleAssignmentProviderOpencode RoleAssignmentProvider = "opencode"
)

// Valid indicates whether the value is a known member of the RoleAssignmentProvider enum.
func (e RoleAssignmentProvider) Valid() bool {
	switch e {
	case RoleAssignmentProviderCodex:
		return true
	case RoleAssignmentProviderOpencode:
		return true
	default:
		return false
	}
}

// Defines values for RunRecordMode.
const (
	Complete   RunRecordMode = "complete"
	Context    RunRecordMode = "context"
	Diff       RunRecordMode = "diff"
	Exhaustive RunRecordMode = "exhaustive"
	Manual     RunRecordMode = "manual"
)

// Valid indicates whether the value is a known member of the RunRecordMode enum.
func (e RunRecordMode) Valid() bool {
	switch e {
	case Complete:
		return true
	case Context:
		return true
	case Diff:
		return true
	case Exhaustive:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for RunRecordStatus.
const (
	Done     RunRecordStatus = "done"
	Enqueued RunRecordStatus = "enqueued"
	Running  RunRecordStatus = "running"
)

// Valid indicates whether the value is a known member of the RunRecordStatus enum.
func (e RunRecordStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case Enqueued:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for RunRecordTarget.
const (
	RunRecordTargetCode RunRecordTarget = "code"
	RunRecordTargetE2e  RunRecordTarget = "e2e"
)

// Valid indicates whether the value is a known member of the RunRecordTarget enum.
func (e RunRecordTarget) Valid() bool {
	switch e {
	case RunRecordTargetCode:
		return true
	case RunRecordTargetE2e:
		return true
	default:
		return false
	}
}

// Defines values for RunRecordVerdict.
const (
	RunRecordVerdictFail       RunRecordVerdict = "fail"
	RunRecordVerdictFlaky      RunRecordVerdict = "flaky"
	RunRecordVerdictInfraError RunRecordVerdict = "infra-error"
	RunRecordVerdictInvalid    RunRecordVerdict = "invalid"
	RunRecordVerdictPass       RunRecordVerdict = "pass"
	RunRecordVerdictSkipped    RunRecordVerdict = "skipped"
)

// Valid indicates whether the value is a known member of the RunRecordVerdict enum.
func (e RunRecordVerdict) Valid() bool {
	switch e {
	case RunRecordVerdictFail:
		return true
	case RunRecordVerdictFlaky:
		return true
	case RunRecordVerdictInfraError:
		return true
	case RunRecordVerdictInvalid:
		return true
	case RunRecordVerdictPass:
		return true
	case RunRecordVerdictSkipped:
		return true
	default:
		return false
	}
}

// Defines values for UpdateAppInputTarget.
const (
	Code UpdateAppInputTarget = "code"
	E2e  UpdateAppInputTarget = "e2e"
)

// Valid indicates whether the value is a known member of the UpdateAppInputTarget enum.
func (e UpdateAppInputTarget) Valid() bool {
	switch e {
	case Code:
		return true
	case E2e:
		return true
	default:
		return false
	}
}

// Defines values for ListAgentModelsParamsProvider.
const (
	ListAgentModelsParamsProviderCodex    ListAgentModelsParamsProvider = "codex"
	ListAgentModelsParamsProviderOpencode ListAgentModelsParamsProvider = "opencode"
)

// Valid indicates whether the value is a known member of the ListAgentModelsParamsProvider enum.
func (e ListAgentModelsParamsProvider) Valid() bool {
	switch e {
	case ListAgentModelsParamsProviderCodex:
		return true
	case ListAgentModelsParamsProviderOpencode:
		return true
	default:
		return false
	}
}

// AgentActivity defines model for AgentActivity.
type AgentActivity struct {
	Kind   AgentActivityKind    `json:"kind"`
	Status *AgentActivityStatus `json:"status,omitempty"`
	Text   string               `json:"text"`
	Ts     string               `json:"ts"`
}

// AgentActivityKind defines model for AgentActivity.Kind.
type AgentActivityKind string

// AgentActivityStatus defines model for AgentActivity.Status.
type AgentActivityStatus string

// AgentConfigApplyResult defines model for AgentConfigApplyResult.
type AgentConfigApplyResult struct {
	Config     PublicAgentConfig                 `json:"config"`
	Downgraded *bool                             `json:"downgraded,omitempty"`
	Restarted  []AgentConfigApplyResultRestarted `json:"restarted"`
}

// AgentConfigApplyResultRestarted defines model for AgentConfigApplyResult.Restarted.
type AgentConfigApplyResultRestarted string

// AgentConfigUpdate defines model for AgentConfigUpdate.
type AgentConfigUpdate struct {
	ApiKeys *struct {
		Codex    *string `json:"codex,omitempty"`
		Opencode *string `json:"opencode,omitempty"`
	} `json:"apiKeys,omitempty"`
	Assignments *struct {
		Chat     *RoleAssignment `json:"chat,omitempty"`
		Primary  *RoleAssignment `json:"primary,omitempty"`
		Reviewer *RoleAssignment `json:"reviewer,omitempty"`
	} `json:"assignments,omitempty"`
	ConfirmSingleDowngrade *bool                            `json:"confirmSingleDowngrade,omitempty"`
	Mode                   *AgentConfigUpdateMode           `json:"mode,omitempty"`
	SingleProvider         *AgentConfigUpdateSingleProvider `json:"singleProvider,omitempty"`
}

// AgentConfigUpdateMode defines model for AgentConfigUpdate.Mode.
type AgentConfigUpdateMode string

// AgentConfigUpdateSingleProvider defines model for AgentConfigUpdate.SingleProvider.
type AgentConfigUpdateSingleProvider string

// AgentModelInfo defines model for AgentModelInfo.
type AgentModelInfo struct {
	Id       string                  `json:"id"`
	Label    *string                 `json:"label,omitempty"`
	Provider *AgentModelInfoProvider `json:"provider,omitempty"`
}

// AgentModelInfoProvider defines model for AgentModelInfo.Provider.
type AgentModelInfoProvider string

// AgentModelsResponse defines model for AgentModelsResponse.
type AgentModelsResponse struct {
	Models   []AgentModelInfo            `json:"models"`
	Provider AgentModelsResponseProvider `json:"provider"`
}

// AgentModelsResponseProvider defines model for AgentModelsResponse.Provider.
type AgentModelsResponseProvider string

// AgentProviderHealth defines model for AgentProviderHealth.
type AgentProviderHealth struct {
	Configured bool                        `json:"configured"`
	Error      *string                     `json:"error,omitempty"`
	Provider   AgentProviderHealthProvider `json:"provider"`
	Status     AgentProviderHealthStatus   `json:"status"`
}

// AgentProviderHealthProvider defines model for AgentProviderHealth.Provider.
type AgentProviderHealthProvider string

// AgentProviderHealthStatus defines model for AgentProviderHealth.Status.
type AgentProviderHealthStatus string

// AgentRestartRequest defines model for AgentRestartRequest.
type AgentRestartRequest struct {
	Provider AgentRestartRequestProvider `json:"provider"`
}

// AgentRestartRequestProvider defines model for AgentRestartRequest.Provider.
type AgentRestartRequestProvider string

// AgentRestartResponse defines model for AgentRestartResponse.
type AgentRestartResponse struct {
	Health AgentProviderHealth `json:"health"`
}

// AppService defines model for AppService.
type AppService struct {
	Openapi    *string `json:"openapi,omitempty"`
	Repo       string  `json:"repo"`
	VersionUrl *string `json:"versionUrl,omitempty"`
}

// AppView defines model for AppView.
type AppView struct {
	BaseUrl        string       `json:"baseUrl"`
	Code           bool         `json:"code"`
	Name           string       `json:"name"`
	NeedsReview    bool         `json:"needsReview"`
	Repo           string       `json:"repo"`
	Services       []AppService `json:"services"`
	Shadow         bool         `json:"shadow"`
	TestDataPrefix string       `json:"testDataPrefix"`
	VersionUrl     string       `json:"versionUrl"`
}

// AskRequest defines model for AskRequest.
type AskRequest struct {
	History  *[]ChatEntry `json:"history,omitempty"`
	Question string       `json:"question"`
}

// AskResponse defines model for AskResponse.
type AskResponse struct {
	Answer string `json:"answer"`
}

// ChatEntry defines model for ChatEntry.
type ChatEntry struct {
	Role string `json:"role"`
	Text string `json:"text"`
}

// ContinueRequest defines model for ContinueRequest.
type ContinueRequest struct {
	Cases    *[]string `json:"cases,omitempty"`
	Guidance *string   `json:"guidance,omitempty"`
}

// ContinueResult defines model for ContinueResult.
type ContinueResult struct {
	Id          string `json:"id"`
	ParentRunId string `json:"parentRunId"`
}

// CreateAppInput defines model for CreateAppInput.
type CreateAppInput struct {
	BaseUrl        *string                `json:"baseUrl,omitempty"`
	DryRun         *bool                  `json:"dryRun,omitempty"`
	Env            *map[string]string     `json:"env,omitempty"`
	Name           *string                `json:"name,omitempty"`
	NeedsReview    *bool                  `json:"needsReview,omitempty"`
	Repo           string                 `json:"repo"`
	Services       *[]OnboardServiceInput `json:"services,omitempty"`
	Shadow         *bool                  `json:"shadow,omitempty"`
	Target         *CreateAppInputTarget  `json:"target,omitempty"`
	TestDataPrefix *string                `json:"testDataPrefix,omitempty"`
	ValidateOnly   *bool                  `json:"validateOnly,omitempty"`
	VersionUrl     *string                `json:"versionUrl,omitempty"`
}

// CreateAppInputTarget defines model for CreateAppInput.Target.
type CreateAppInputTarget string

// CreateAppResult defines model for CreateAppResult.
type CreateAppResult struct {
	EnvApplied *[]string `json:"envApplied,omitempty"`
	Errors     *[]string `json:"errors,omitempty"`
	Name       *string   `json:"name,omitempty"`
	Ok         bool      `json:"ok"`
	Path       *string   `json:"path,omitempty"`
	RepoInfo   *RepoInfo `json:"repoInfo,omitempty"`
	Warnings   *[]string `json:"warnings,omitempty"`
	Yaml       *string   `json:"yaml,omitempty"`
}

// CreateRunInput defines model for CreateRunInput.
type CreateRunInput struct {
	App      string               `json:"app"`
	Commits  *int                 `json:"commits,omitempty"`
	Guidance *string              `json:"guidance,omitempty"`
	Mode     CreateRunInputMode   `json:"mode"`
	Ref      *string              `json:"ref,omitempty"`
	Sha      *string              `json:"sha,omitempty"`
	Shadow   *bool                `json:"shadow,omitempty"`
	Target   CreateRunInputTarget `json:"target"`
}

// CreateRunInputMode defines model for CreateRunInput.Mode.
type CreateRunInputMode string

// CreateRunInputTarget defines model for CreateRunInput.Target.
type CreateRunInputTarget string

// CreateRunResult defines model for CreateRunResult.
type CreateRunResult struct {
	App    string                `json:"app"`
	Id     string                `json:"id"`
	Mode   CreateRunResultMode   `json:"mode"`
	Sha    string                `json:"sha"`
	Status string                `json:"status"`
	Target CreateRunResultTarget `json:"target"`
}

// CreateRunResultMode defines model for CreateRunResult.Mode.
type CreateRunResultMode string

// CreateRunResultTarget defines model for CreateRunResult.Target.
type CreateRunResultTarget string

// CurriculumView defines model for CurriculumView.
type CurriculumView struct {
	Archetypes []struct {
		Archetype      string `json:"archetype"`
		CaughtRealBug  bool   `json:"caughtRealBug"`
		PromotionCount int    `json:"promotionCount"`
	} `json:"archetypes"`
	UpdatedAt string `json:"updatedAt"`
}

// DeleteAppResult defines model for DeleteAppResult.
type DeleteAppResult struct {
	Removed []string `json:"removed"`
}

// IntelligenceView defines model for IntelligenceView.
type IntelligenceView struct {
	App        string             `json:"app"`
	Curriculum *CurriculumView    `json:"curriculum"`
	Rules      []LearningRuleView `json:"rules"`
	Scorecard  *ScorecardView     `json:"scorecard"`
}

// LearningRuleView defines model for LearningRuleView.
type LearningRuleView struct {
	Action       string                     `json:"action"`
	Confidence   LearningRuleViewConfidence `json:"confidence"`
	ErrorClass   string                     `json:"errorClass"`
	OutcomeCount int                        `json:"outcomeCount"`
	Status       LearningRuleViewStatus     `json:"status"`
	SuccessRate  *float32                   `json:"successRate"`
	Trigger      string                     `json:"trigger"`
	UsageCount   int                        `json:"usageCount"`
}

// LearningRuleViewConfidence defines model for LearningRuleView.Confidence.
type LearningRuleViewConfidence string

// LearningRuleViewStatus defines model for LearningRuleView.Status.
type LearningRuleViewStatus string

// OnboardServiceInput defines model for OnboardServiceInput.
type OnboardServiceInput struct {
	Openapi    *string `json:"openapi,omitempty"`
	Repo       string  `json:"repo"`
	VersionUrl *string `json:"versionUrl,omitempty"`
}

// PublicAgentConfig defines model for PublicAgentConfig.
type PublicAgentConfig struct {
	Assignments struct {
		Chat     RoleAssignment `json:"chat"`
		Primary  RoleAssignment `json:"primary"`
		Reviewer RoleAssignment `json:"reviewer"`
	} `json:"assignments"`
	Health *struct {
		Codex    *AgentProviderHealth `json:"codex,omitempty"`
		Opencode *AgentProviderHealth `json:"opencode,omitempty"`
	} `json:"health,omitempty"`
	Keys struct {
		Codex    bool `json:"codex"`
		Opencode bool `json:"opencode"`
	} `json:"keys"`
	Mode           PublicAgentConfigMode           `json:"mode"`
	SingleProvider PublicAgentConfigSingleProvider `json:"singleProvider"`
	Validation     struct {
		DowngradeProvider                   *PublicAgentConfigValidationDowngradeProvider `json:"downgradeProvider,omitempty"`
		Errors                              []string                                      `json:"errors"`
		Ok                                  bool                                          `json:"ok"`
		RequiresSingleDowngradeConfirmation *bool                                         `json:"requiresSingleDowngradeConfirmation,omitempty"`
	} `json:"validation"`
}

// PublicAgentConfigMode defines model for PublicAgentConfig.Mode.
type PublicAgentConfigMode string

// PublicAgentConfigSingleProvider defines model for PublicAgentConfig.SingleProvider.
type PublicAgentConfigSingleProvider string

// PublicAgentConfigValidationDowngradeProvider defines model for PublicAgentConfig.Validation.DowngradeProvider.
type PublicAgentConfigValidationDowngradeProvider string

// QaCase defines model for QaCase.
type QaCase struct {
	Detail     *string      `json:"detail,omitempty"`
	DurationMs *float32     `json:"durationMs,omitempty"`
	Flow       *string      `json:"flow,omitempty"`
	Name       string       `json:"name"`
	Objective  *string      `json:"objective,omitempty"`
	Reason     *string      `json:"reason,omitempty"`
	Status     QaCaseStatus `json:"status"`
}

// QaCaseStatus defines model for QaCase.Status.
type QaCaseStatus string

// QueueStatus defines model for QueueStatus.
type QueueStatus struct {
	Pending int `json:"pending"`
	Running *struct {
		App string `json:"app"`
		Id  string `json:"id"`
	} `json:"running"`
}

// RepoInfo defines model for RepoInfo.
type RepoInfo struct {
	DefaultBranch string  `json:"defaultBranch"`
	Description   *string `json:"description"`
	FullName      string  `json:"fullName"`
	Name          string  `json:"name"`
	Private       bool    `json:"private"`
}

// RepoListItem defines model for RepoListItem.
type RepoListItem struct {
	Description *string `json:"description"`
	FullName    string  `json:"fullName"`
	Private     bool    `json:"private"`
}

// RepoListResponse defines model for RepoListResponse.
type RepoListResponse struct {
	HasMore bool           `json:"hasMore"`
	Repos   []RepoListItem `json:"repos"`
}

// RoleAssignment defines model for RoleAssignment.
type RoleAssignment struct {
	Model    string                 `json:"model"`
	Provider RoleAssignmentProvider `json:"provider"`
}

// RoleAssignmentProvider defines model for RoleAssignment.Provider.
type RoleAssignmentProvider string

// RunRecord defines model for RunRecord.
type RunRecord struct {
	Activity      *[]AgentActivity  `json:"activity,omitempty"`
	App           string            `json:"app"`
	At            string            `json:"at"`
	Cases         []QaCase          `json:"cases"`
	Failed        *int              `json:"failed,omitempty"`
	Id            string            `json:"id"`
	Logs          []string          `json:"logs"`
	Mode          RunRecordMode     `json:"mode"`
	Note          *string           `json:"note,omitempty"`
	ParentRunId   *string           `json:"parentRunId,omitempty"`
	Passed        *int              `json:"passed,omitempty"`
	Ref           *string           `json:"ref,omitempty"`
	Retrying      *bool             `json:"retrying,omitempty"`
	Sha           string            `json:"sha"`
	Specs         *[]SpecRecord     `json:"specs,omitempty"`
	Status        RunRecordStatus   `json:"status"`
	Step          *string           `json:"step,omitempty"`
	StepDetail    *string           `json:"stepDetail,omitempty"`
	StepStartedAt *string           `json:"stepStartedAt,omitempty"`
	Target        RunRecordTarget   `json:"target"`
	TriggerRepo   *string           `json:"triggerRepo,omitempty"`
	Verdict       *RunRecordVerdict `json:"verdict,omitempty"`
}

// RunRecordMode defines model for RunRecord.Mode.
type RunRecordMode string

// RunRecordStatus defines model for RunRecord.Status.
type RunRecordStatus string

// RunRecordTarget defines model for RunRecord.Target.
type RunRecordTarget string

// RunRecordVerdict defines model for RunRecord.Verdict.
type RunRecordVerdict string

// ScorecardView defines model for ScorecardView.
type ScorecardView struct {
	AvgValueScore *float32 `json:"avgValueScore"`
	Entries       []struct {
		At          string   `json:"at"`
		KilledCount int      `json:"killedCount"`
		MutantCount int      `json:"mutantCount"`
		Target      string   `json:"target"`
		ValueScore  *float32 `json:"valueScore"`
	} `json:"entries"`
	LastValueScore *float32 `json:"lastValueScore"`
	MeasuredRuns   int      `json:"measuredRuns"`
	TotalRuns      int      `json:"totalRuns"`
	UpdatedAt      string   `json:"updatedAt"`
}

// SignalsView defines model for SignalsView.
type SignalsView struct {
	Coverage struct {
		Measured bool `json:"measured"`
	} `json:"coverage"`
	Reviewer struct {
		PassRate *float32 `json:"passRate"`
		Runs     int      `json:"runs"`
	} `json:"reviewer"`
	ValueOracle struct {
		AvgScore     *float32 `json:"avgScore"`
		Measured     bool     `json:"measured"`
		MeasuredRuns int      `json:"measuredRuns"`
		TotalRuns    int      `json:"totalRuns"`
	} `json:"valueOracle"`
}

// SpecRecord defines model for SpecRecord.
type SpecRecord struct {
	Flow      *string `json:"flow,omitempty"`
	Name      string  `json:"name"`
	Objective *string `json:"objective,omitempty"`
}

// UpdateAppInput defines model for UpdateAppInput.
type UpdateAppInput struct {
	BaseUrl        *string                `json:"baseUrl,omitempty"`
	DryRun         *bool                  `json:"dryRun,omitempty"`
	Env            *map[string]string     `json:"env,omitempty"`
	NeedsReview    *bool                  `json:"needsReview,omitempty"`
	Repo           *string                `json:"repo,omitempty"`
	Services       *[]OnboardServiceInput `json:"services,omitempty"`
	Shadow         *bool                  `json:"shadow,omitempty"`
	Target         *UpdateAppInputTarget  `json:"target,omitempty"`
	TestDataPrefix *string                `json:"testDataPrefix,omitempty"`
	VersionUrl     *string                `json:"versionUrl,omitempty"`
}

// UpdateAppInputTarget defines model for UpdateAppInput.Target.
type UpdateAppInputTarget string

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	ApiVersion       string   `json:"apiVersion"`
	Capabilities     []string `json:"capabilities"`
	Compatible       bool     `json:"compatible"`
	Message          *string  `json:"message,omitempty"`
	MinClientVersion string   `json:"minClientVersion"`
	ServerVersion    string   `json:"serverVersion"`
}

// ListAgentModelsParams defines parameters for ListAgentModels.
type ListAgentModelsParams struct {
	Provider ListAgentModelsParamsProvider `form:"provider" json:"provider"`
}

// ListAgentModelsParamsProvider defines parameters for ListAgentModels.
type ListAgentModelsParamsProvider string

// DeleteAppParams defines parameters for DeleteApp.
type DeleteAppParams struct {
	Purge *bool `form:"purge,omitempty" json:"purge,omitempty"`
}

// ListReposParams defines parameters for ListRepos.
type ListReposParams struct {
	Owner string `form:"owner" json:"owner"`
	Page  *int   `form:"page,omitempty" json:"page,omitempty"`
}

// ListRunsParams defines parameters for ListRuns.
type ListRunsParams struct {
	App   string `form:"app" json:"app"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamRunEventsParams defines parameters for StreamRunEvents.
type StreamRunEventsParams struct {
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

// HandshakeParams defines parameters for Handshake.
type HandshakeParams struct {
	Client *string `form:"client,omitempty" json:"client,omitempty"`
}

// UpdateAgentConfigJSONRequestBody defines body for UpdateAgentConfig for application/json ContentType.
type UpdateAgentConfigJSONRequestBody = AgentConfigUpdate

// RestartAgentProviderJSONRequestBody defines body for RestartAgentProvider for application/json ContentType.
type RestartAgentProviderJSONRequestBody = AgentRestartRequest

// CreateAppJSONRequestBody defines body for CreateApp for application/json ContentType.
type CreateAppJSONRequestBody = CreateAppInput

// UpdateAppJSONRequestBody defines body for UpdateApp for application/json ContentType.
type UpdateAppJSONRequestBody = UpdateAppInput

// HelpJSONRequestBody defines body for Help for application/json ContentType.
type HelpJSONRequestBody = AskRequest

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRunInput

// AskRunJSONRequestBody defines body for AskRun for application/json ContentType.
type AskRunJSONRequestBody = AskRequest

// ContinueRunJSONRequestBody defines body for ContinueRun for application/json ContentType.
type ContinueRunJSONRequestBody = ContinueRequest
