// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package contract

// Defines values for AgentActivityKind.
const (
	Command AgentActivityKind = "command"
	Error   AgentActivityKind = "error"
	File    AgentActivityKind = "file"
	Phase   AgentActivityKind = "phase"
	Todo    AgentActivityKind = "todo"
)

// Valid indicates whether the value is a known member of the AgentActivityKind enum.
func (e AgentActivityKind) Valid() bool {
	switch e {
	case Command:
		return true
	case Error:
		return true
	case File:
		return true
	case Phase:
		return true
	case Todo:
		return true
	default:
		return false
	}
}

// Defines values for AgentActivityStatus.
const (
	Completed  AgentActivityStatus = "completed"
	InProgress AgentActivityStatus = "in_progress"
	Pending    AgentActivityStatus = "pending"
)

// Valid indicates whether the value is a known member of the AgentActivityStatus enum.
func (e AgentActivityStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case InProgress:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for CreateRunInputMode.
const (
	CreateRunInputModeComplete   CreateRunInputMode = "complete"
	CreateRunInputModeContext    CreateRunInputMode = "context"
	CreateRunInputModeDiff       CreateRunInputMode = "diff"
	CreateRunInputModeExhaustive CreateRunInputMode = "exhaustive"
	CreateRunInputModeManual     CreateRunInputMode = "manual"
)

// Valid indicates whether the value is a known member of the CreateRunInputMode enum.
func (e CreateRunInputMode) Valid() bool {
	switch e {
	case CreateRunInputModeComplete:
		return true
	case CreateRunInputModeContext:
		return true
	case CreateRunInputModeDiff:
		return true
	case CreateRunInputModeExhaustive:
		return true
	case CreateRunInputModeManual:
		return true
	default:
		return false
	}
}

// Defines values for CreateRunInputTarget.
const (
	CreateRunInputTargetCode CreateRunInputTarget = "code"
	CreateRunInputTargetE2e  CreateRunInputTarget = "e2e"
)

// Valid indicates whether the value is a known member of the CreateRunInputTarget enum.
func (e CreateRunInputTarget) Valid() bool {
	switch e {
	case CreateRunInputTargetCode:
		return true
	case CreateRunInputTargetE2e:
		return true
	default:
		return false
	}
}

// Defines values for CreateRunResultMode.
const (
	CreateRunResultModeComplete   CreateRunResultMode = "complete"
	CreateRunResultModeContext    CreateRunResultMode = "context"
	CreateRunResultModeDiff       CreateRunResultMode = "diff"
	CreateRunResultModeExhaustive CreateRunResultMode = "exhaustive"
	CreateRunResultModeManual     CreateRunResultMode = "manual"
)

// Valid indicates whether the value is a known member of the CreateRunResultMode enum.
func (e CreateRunResultMode) Valid() bool {
	switch e {
	case CreateRunResultModeComplete:
		return true
	case CreateRunResultModeContext:
		return true
	case CreateRunResultModeDiff:
		return true
	case CreateRunResultModeExhaustive:
		return true
	case CreateRunResultModeManual:
		return true
	default:
		return false
	}
}

// Defines values for CreateRunResultTarget.
const (
	CreateRunResultTargetCode CreateRunResultTarget = "code"
	CreateRunResultTargetE2e  CreateRunResultTarget = "e2e"
)

// Valid indicates whether the value is a known member of the CreateRunResultTarget enum.
func (e CreateRunResultTarget) Valid() bool {
	switch e {
	case CreateRunResultTargetCode:
		return true
	case CreateRunResultTargetE2e:
		return true
	default:
		return false
	}
}

// Defines values for QaCaseStatus.
const (
	QaCaseStatusFail  QaCaseStatus = "fail"
	QaCaseStatusFlaky QaCaseStatus = "flaky"
	QaCaseStatusPass  QaCaseStatus = "pass"
)

// Valid indicates whether the value is a known member of the QaCaseStatus enum.
func (e QaCaseStatus) Valid() bool {
	switch e {
	case QaCaseStatusFail:
		return true
	case QaCaseStatusFlaky:
		return true
	case QaCaseStatusPass:
		return true
	default:
		return false
	}
}

// Defines values for RunRecordMode.
const (
	Complete   RunRecordMode = "complete"
	Context    RunRecordMode = "context"
	Diff       RunRecordMode = "diff"
	Exhaustive RunRecordMode = "exhaustive"
	Manual     RunRecordMode = "manual"
)

// Valid indicates whether the value is a known member of the RunRecordMode enum.
func (e RunRecordMode) Valid() bool {
	switch e {
	case Complete:
		return true
	case Context:
		return true
	case Diff:
		return true
	case Exhaustive:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for RunRecordStatus.
const (
	Done     RunRecordStatus = "done"
	Enqueued RunRecordStatus = "enqueued"
	Running  RunRecordStatus = "running"
)

// Valid indicates whether the value is a known member of the RunRecordStatus enum.
func (e RunRecordStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case Enqueued:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for RunRecordTarget.
const (
	Code RunRecordTarget = "code"
	E2e  RunRecordTarget = "e2e"
)

// Valid indicates whether the value is a known member of the RunRecordTarget enum.
func (e RunRecordTarget) Valid() bool {
	switch e {
	case Code:
		return true
	case E2e:
		return true
	default:
		return false
	}
}

// Defines values for RunRecordVerdict.
const (
	RunRecordVerdictFail       RunRecordVerdict = "fail"
	RunRecordVerdictFlaky      RunRecordVerdict = "flaky"
	RunRecordVerdictInfraError RunRecordVerdict = "infra-error"
	RunRecordVerdictInvalid    RunRecordVerdict = "invalid"
	RunRecordVerdictPass       RunRecordVerdict = "pass"
	RunRecordVerdictSkipped    RunRecordVerdict = "skipped"
)

// Valid indicates whether the value is a known member of the RunRecordVerdict enum.
func (e RunRecordVerdict) Valid() bool {
	switch e {
	case RunRecordVerdictFail:
		return true
	case RunRecordVerdictFlaky:
		return true
	case RunRecordVerdictInfraError:
		return true
	case RunRecordVerdictInvalid:
		return true
	case RunRecordVerdictPass:
		return true
	case RunRecordVerdictSkipped:
		return true
	default:
		return false
	}
}

// AgentActivity defines model for AgentActivity.
type AgentActivity struct {
	Kind   AgentActivityKind    `json:"kind"`
	Status *AgentActivityStatus `json:"status,omitempty"`
	Text   string               `json:"text"`
	Ts     string               `json:"ts"`
}

// AgentActivityKind defines model for AgentActivity.Kind.
type AgentActivityKind string

// AgentActivityStatus defines model for AgentActivity.Status.
type AgentActivityStatus string

// AppService defines model for AppService.
type AppService struct {
	Openapi    *string `json:"openapi,omitempty"`
	Repo       string  `json:"repo"`
	VersionUrl *string `json:"versionUrl,omitempty"`
}

// AppView defines model for AppView.
type AppView struct {
	BaseUrl        string       `json:"baseUrl"`
	Code           bool         `json:"code"`
	Name           string       `json:"name"`
	NeedsReview    bool         `json:"needsReview"`
	Repo           string       `json:"repo"`
	Services       []AppService `json:"services"`
	Shadow         bool         `json:"shadow"`
	TestDataPrefix string       `json:"testDataPrefix"`
	VersionUrl     string       `json:"versionUrl"`
}

// AskRequest defines model for AskRequest.
type AskRequest struct {
	History  *[]ChatEntry `json:"history,omitempty"`
	Question string       `json:"question"`
}

// AskResponse defines model for AskResponse.
type AskResponse struct {
	Answer string `json:"answer"`
}

// ChatEntry defines model for ChatEntry.
type ChatEntry struct {
	Role string `json:"role"`
	Text string `json:"text"`
}

// ContinueRequest defines model for ContinueRequest.
type ContinueRequest struct {
	Cases    *[]string `json:"cases,omitempty"`
	Guidance *string   `json:"guidance,omitempty"`
}

// ContinueResult defines model for ContinueResult.
type ContinueResult struct {
	Id          string `json:"id"`
	ParentRunId string `json:"parentRunId"`
}

// CreateRunInput defines model for CreateRunInput.
type CreateRunInput struct {
	App      string               `json:"app"`
	Guidance *string              `json:"guidance,omitempty"`
	Mode     CreateRunInputMode   `json:"mode"`
	Ref      *string              `json:"ref,omitempty"`
	Sha      *string              `json:"sha,omitempty"`
	Shadow   *bool                `json:"shadow,omitempty"`
	Target   CreateRunInputTarget `json:"target"`
}

// CreateRunInputMode defines model for CreateRunInput.Mode.
type CreateRunInputMode string

// CreateRunInputTarget defines model for CreateRunInput.Target.
type CreateRunInputTarget string

// CreateRunResult defines model for CreateRunResult.
type CreateRunResult struct {
	App    string                `json:"app"`
	Id     string                `json:"id"`
	Mode   CreateRunResultMode   `json:"mode"`
	Sha    string                `json:"sha"`
	Status string                `json:"status"`
	Target CreateRunResultTarget `json:"target"`
}

// CreateRunResultMode defines model for CreateRunResult.Mode.
type CreateRunResultMode string

// CreateRunResultTarget defines model for CreateRunResult.Target.
type CreateRunResultTarget string

// QaCase defines model for QaCase.
type QaCase struct {
	Detail     *string      `json:"detail,omitempty"`
	DurationMs *float32     `json:"durationMs,omitempty"`
	Flow       *string      `json:"flow,omitempty"`
	Name       string       `json:"name"`
	Objective  *string      `json:"objective,omitempty"`
	Reason     *string      `json:"reason,omitempty"`
	Status     QaCaseStatus `json:"status"`
}

// QaCaseStatus defines model for QaCase.Status.
type QaCaseStatus string

// QueueStatus defines model for QueueStatus.
type QueueStatus struct {
	Pending int `json:"pending"`
	Running *struct {
		App string `json:"app"`
		Id  string `json:"id"`
	} `json:"running"`
}

// RunRecord defines model for RunRecord.
type RunRecord struct {
	Activity      *[]AgentActivity  `json:"activity,omitempty"`
	App           string            `json:"app"`
	At            string            `json:"at"`
	Cases         []QaCase          `json:"cases"`
	Failed        *int              `json:"failed,omitempty"`
	Id            string            `json:"id"`
	Logs          []string          `json:"logs"`
	Mode          RunRecordMode     `json:"mode"`
	Note          *string           `json:"note,omitempty"`
	ParentRunId   *string           `json:"parentRunId,omitempty"`
	Passed        *int              `json:"passed,omitempty"`
	Ref           *string           `json:"ref,omitempty"`
	Retrying      *bool             `json:"retrying,omitempty"`
	Sha           string            `json:"sha"`
	Specs         *[]SpecRecord     `json:"specs,omitempty"`
	Status        RunRecordStatus   `json:"status"`
	Step          *string           `json:"step,omitempty"`
	StepDetail    *string           `json:"stepDetail,omitempty"`
	StepStartedAt *string           `json:"stepStartedAt,omitempty"`
	Target        RunRecordTarget   `json:"target"`
	TriggerRepo   *string           `json:"triggerRepo,omitempty"`
	Verdict       *RunRecordVerdict `json:"verdict,omitempty"`
}

// RunRecordMode defines model for RunRecord.Mode.
type RunRecordMode string

// RunRecordStatus defines model for RunRecord.Status.
type RunRecordStatus string

// RunRecordTarget defines model for RunRecord.Target.
type RunRecordTarget string

// RunRecordVerdict defines model for RunRecord.Verdict.
type RunRecordVerdict string

// SpecRecord defines model for SpecRecord.
type SpecRecord struct {
	Flow      *string `json:"flow,omitempty"`
	Name      string  `json:"name"`
	Objective *string `json:"objective,omitempty"`
}

// ListRunsParams defines parameters for ListRuns.
type ListRunsParams struct {
	App   string `form:"app" json:"app"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamRunEventsParams defines parameters for StreamRunEvents.
type StreamRunEventsParams struct {
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

// HelpJSONRequestBody defines body for Help for application/json ContentType.
type HelpJSONRequestBody = AskRequest

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRunInput

// AskRunJSONRequestBody defines body for AskRun for application/json ContentType.
type AskRunJSONRequestBody = AskRequest

// ContinueRunJSONRequestBody defines body for ContinueRun for application/json ContentType.
type ContinueRunJSONRequestBody = ContinueRequest
